{% raw %}
scrape_configs:
  - job_name: rabbit
    static_configs:
      - targets:
{% for host in groups['rabbitmq'] %}
        - '{{ 'api' | kolla_address(host) | put_address_in_context('url') }}:15692'
{% endfor %}
{% endraw %}